"""empty message

Revision ID: 21301e699f9b
Revises: c6ee10011732
Create Date: 2024-11-23 22:16:49.195204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21301e699f9b'
down_revision = 'c6ee10011732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyacivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('week', sa.String(length=2), nullable=True),
    sa.Column('date', sa.String(length=2), nullable=True),
    sa.Column('day', sa.String(length=3), nullable=True),
    sa.Column('time', sa.String(length=4), nullable=True),
    sa.Column('activity', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dailyacivity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dailyacivity_email'), ['email'], unique=False)

    with op.batch_alter_table('roleplay', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('roleweek', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('order', sa.String(length=4), nullable=True))
        batch_op.drop_index('ix_roleweek_week')
        batch_op.drop_index('ix_roleweek_year')
        batch_op.drop_column('date')
        batch_op.drop_column('day')
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roleweek', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', mysql.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('day', mysql.VARCHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('date', mysql.VARCHAR(length=2), nullable=True))
        batch_op.create_index('ix_roleweek_year', ['year'], unique=False)
        batch_op.create_index('ix_roleweek_week', ['week'], unique=False)
        batch_op.drop_column('order')
        batch_op.drop_column('role')

    with op.batch_alter_table('roleplay', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('dailyacivity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dailyacivity_email'))

    op.drop_table('dailyacivity')
    # ### end Alembic commands ###
