"""empty message

Revision ID: b6d2593eabba
Revises: ed85dd6a8516
Create Date: 2024-12-24 11:46:14.989386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6d2593eabba'
down_revision = 'ed85dd6a8516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roleplay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=500), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roleplay', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
