"""empty message

Revision ID: c6ee10011732
Revises: c74a381058c9
Create Date: 2024-11-23 21:33:36.656238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ee10011732'
down_revision = 'c74a381058c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roleplay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('principal', sa.String(length=2000), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roleplay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roleplay_email'), ['email'], unique=False)

    op.create_table('roleweek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('week', sa.String(length=2), nullable=True),
    sa.Column('date', sa.String(length=2), nullable=True),
    sa.Column('day', sa.String(length=3), nullable=True),
    sa.Column('time', sa.String(length=4), nullable=True),
    sa.Column('activity', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roleweek', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roleweek_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_roleweek_week'), ['week'], unique=False)
        batch_op.create_index(batch_op.f('ix_roleweek_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roleweek', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roleweek_year'))
        batch_op.drop_index(batch_op.f('ix_roleweek_week'))
        batch_op.drop_index(batch_op.f('ix_roleweek_email'))

    op.drop_table('roleweek')
    with op.batch_alter_table('roleplay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roleplay_email'))

    op.drop_table('roleplay')
    # ### end Alembic commands ###
