"""empty message

Revision ID: e0d9a64995b9
Revises: 21301e699f9b
Create Date: 2024-11-23 23:06:01.375219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0d9a64995b9'
down_revision = '21301e699f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('week', sa.String(length=2), nullable=True),
    sa.Column('date', sa.String(length=2), nullable=True),
    sa.Column('day', sa.String(length=3), nullable=True),
    sa.Column('time', sa.String(length=4), nullable=True),
    sa.Column('activity', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dailyactivity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dailyactivity_email'), ['email'], unique=False)

    with op.batch_alter_table('dailyacivity', schema=None) as batch_op:
        batch_op.drop_index('ix_dailyacivity_email')

    op.drop_table('dailyacivity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyacivity',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('week', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('day', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('activity', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('create_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dailyacivity', schema=None) as batch_op:
        batch_op.create_index('ix_dailyacivity_email', ['email'], unique=False)

    with op.batch_alter_table('dailyactivity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dailyactivity_email'))

    op.drop_table('dailyactivity')
    # ### end Alembic commands ###
