"""empty message

Revision ID: ed85dd6a8516
Revises: e60adf352d92
Create Date: 2024-12-01 21:17:25.929226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed85dd6a8516'
down_revision = 'e60adf352d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habbit7', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habbit7', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
